### ISSUE TITLE
not able to login as admin and execute commands

### ISSUE THREAD

**Issue by xXValiXx** [motey/Ark-docker#2]

**Comment by xXValiXx** [comment]
I am not able to login as admin with "admincheats password" on the commandline in the game, the arkmanager rcon-cmd doesnt work either.

**Comment by xXValiXx** [comment]
- [ ] arkmanager rcon-cmd
- [ ] admincheats with commandline ingame

**Comment by motey** [comment]
thanks for the feedback. Please describe a step-by-step workflow how i can replicate/verify the issue.

**Comment by xXValiXx** [comment]
I installed the Server as described on the Readme. Did nothing change anything to the Server. My Server is a Centos 7 Server with 8 Core and 32GB Ram. Need more info?

**Comment by motey** [comment]
> Need more info?

Yes, indeed :) As i said, a step by step workflow. for example:

* Start a server V.abc with map xyz and following GameSettings: ....
* Join with Ark client
* Build this and that

Expected behavior:
i'll get abc

Actual behavior:
abc does not appear

Some background: People usually maintain stuff like this in their spare time out of pure kindness for users they dont know and never here of.
Therefore it would be nice if these users put some effort in a bug report and try to make it easy and fast for the maintainers to pinpoint the issue. With your current bug report i would need to invest time in "whats this 'admincheats password'" and try to find a way to pinpoint and verify the issue and fix it if necessary. this would need 1-2 hours. 
If you write a good replication case - with some links to ark server documentation, and some background knowledge you have and i maybe dont - i just need 20 minutes, because i probably dont need to care whats an  'admincheats password'. 
i just need then follow the strings, you gave me, and fix any broken if i find them.

**Comment by xXValiXx** [comment]
I did test the docker now for a while. Maybe i did something wrong. With a new docker rconcmd is working fine for me. Sorry for the late answer
